sllidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/ttyUSB0
    serial_baudrate: 460800
    frame_id: laser_link
    inverted: false
    angle_compensate: true
    scan_mode: Standard
